"""
⚡ JARVIS PROACTIVE AGENCY — ORCHESTRATOR ENGINE ⚡
The central intelligence daemon that monitors, decides, and speaks.

Architecture
────────────
1. Spawns monitor plugins from ``core.monitors.*`` based on ``proactive_config.json``
2. Each monitor pushes ``ProactiveEvent`` tuples into a shared ``PriorityQueue``
3. The orchestrator drains the queue every 5 s, applies cooldown / quiet-hour
   rules, then dispatches surviving events to the UI toast signal, the WebSocket
   broadcast channel, and (for priority ≤ 3) the JARVIS voice engine.
"""

import threading
import time
import queue
import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from core.jarvis_logger import log_warn

# ⚡ Global queue reference — lets monitors push events directly
# (set to the real PriorityQueue when ProactiveOrchestrator starts)
_GLOBAL_EVENT_QUEUE = None


# ─────────────────────────────────────────────
#  Proactive Event dataclass
# ─────────────────────────────────────────────

@dataclass
class ProactiveEvent:
    """A proactive alert event generated by a monitor.

    Attributes:
        priority:  Severity level — 1 = CRITICAL … 5 = INFO.
        category:  Event domain (system, activity, time, file, network,
                   market, weather, battery, briefing …).
        title:     Short title for UI toast / notification card.
        message:   Full message intended for TTS narration.
        data:      Arbitrary payload dict for downstream consumers.
        timestamp: Unix epoch when the event was created.
    """
    priority: int = 5
    category: str = ""
    title: str = ""
    message: str = ""
    data: dict = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    # PriorityQueue needs items to be comparable.  Lower priority number
    # means higher urgency, so we sort ascending.
    def __lt__(self, other):
        if not isinstance(other, ProactiveEvent):
            return NotImplemented
        return self.priority < other.priority


class OrchestratorEvent:
    """Convenience dispatcher for agent and subsystem events."""
    @classmethod
    def fire(cls, category: str, title: str, message: str, priority: int = 4, data: dict = None):
        global _GLOBAL_EVENT_QUEUE
        try:
            ev = ProactiveEvent(
                priority=priority,
                category=category,
                title=title,
                message=message,
                data=data or {}
            )
            if _GLOBAL_EVENT_QUEUE is not None:
                _GLOBAL_EVENT_QUEUE.put_nowait(ev)
        except Exception as e:
            log_warn("orchestrator_event", f"Failed to fire event: {e}")


# ─────────────────────────────────────────────
#  Orchestrator
# ─────────────────────────────────────────────

class ProactiveOrchestrator(threading.Thread):
    """
    Central Proactive Agency daemon.

    Responsibilities
    ────────────────
    • Spawn and manage all monitor plugins (each is its own daemon thread).
    • Drain the priority event queue every 5 seconds.
    • Apply intelligence rules (cooldowns, context awareness, quiet hours).
    • Output via UI signal + WebSocket + voice.
    """

    # ── class-level priority icon map ──
    PRIORITY_ICONS = {1: "🔴", 2: "🟠", 3: "🟡", 4: "🔵", 5: "⚪"}

    # Cooldown seconds per priority level (CRITICAL never suppressed)
    COOLDOWN_MAP = {1: 300, 2: 900, 3: 1800, 4: 3600, 5: 7200}

    def __init__(self, ui_signal=None):
        super().__init__(daemon=True)
        self.name = "ProactiveOrchestrator"
        self.ui_signal = ui_signal
        self.event_queue: queue.PriorityQueue = queue.PriorityQueue()
        self.monitors: list = []
        self.cooldowns: dict = {}          # category → last_alert_timestamp
        self.config: dict = self._load_config()
        self._stop_event = threading.Event()
        self.event_history: list = []      # Recent events for dashboard
        self.daily_briefing_done: bool = False
        self._event_counter: int = 0       # Tiebreaker for PriorityQueue

        # Fix #11: Voice alert rate limiter
        self._voice_alert_times: list = []   # timestamps of recent spoken alerts
        self._max_voice_per_hour: int = self.config.get("max_alerts_per_hour", 6)
        self._min_voice_gap_sec: int = 60    # minimum 60s between any two spoken alerts

        from concurrent.futures import ThreadPoolExecutor
        self._speak_executor = ThreadPoolExecutor(max_workers=3, thread_name_prefix="ProactiveSpeak")

        # ⚡ Expose queue globally so monitors can push events directly
        global _GLOBAL_EVENT_QUEUE
        _GLOBAL_EVENT_QUEUE = self.event_queue

    # ── Configuration ─────────────────────────

    def _load_config(self) -> dict:
        """Load ``proactive_config.json`` from the project root."""
        config_path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)),
            "proactive_config.json",
        )
        try:
            with open(config_path, "r", encoding="utf-8") as fh:
                cfg = json.load(fh)
                print("[PROACTIVE AGENCY]: Configuration loaded.")
                return cfg
        except FileNotFoundError:
            print("[PROACTIVE]: proactive_config.json not found — using defaults.")
        except json.JSONDecodeError as exc:
            print(f"[PROACTIVE]: Config parse error: {exc} — using defaults.")
        except Exception as exc:
            print(f"[PROACTIVE]: Config load error: {exc} — using defaults.")
        return {
            "enabled": True,
            "monitors": {},
            "quiet_hours": {"enabled": False},
            "max_alerts_per_hour": 10,
            "daily_briefing": {"enabled": True, "spoken": True},
        }

    # ── Monitor initialisation ────────────────

    def _init_monitors(self) -> None:
        """Import and instantiate all monitor plugins based on config."""
        monitor_configs = self.config.get("monitors", {})

        monitors_to_load = [
            ("system_health",     "SystemHealthMonitor"),
            ("digital_activity",  "DigitalActivityMonitor"),
            ("contextual_time",   "ContextualTimeMonitor"),
            ("file_watcher",      "FileSystemWatcher"),
            ("network_sentinel",  "NetworkSentinel"),
            ("market_intel",      "MarketIntelligence"),
            ("weather_awareness", "WeatherAwareness"),
            ("battery_guardian",  "BatteryGuardian"),
            ("dream_mode",        "DreamModeMonitor"),
        ]

        # AGI Extension monitors (loaded from core/ directly, not core/monitors/)
        # NOTE: self_evolution and persistent_vision are intentionally excluded here —
        # they have standalone startup in main.py boot sequence and must not double-start.
        agi_monitors = [
            # Tier 3
            ("web_agent",              "WebAgentMonitor"),
            ("mesh_network",           "MeshNetworkMonitor"),
            # Tier 4 (God Mode)
            ("omni_synthesis",         "OmniSynthesisMonitor"),
        ]

        try:
            from core.feature_flags import is_enabled
        except ImportError:
            is_enabled = lambda name, default=True: True

        for module_name, class_name in monitors_to_load:
            cfg = monitor_configs.get(module_name, {"enabled": True})
            if not cfg.get("enabled", True) or not is_enabled(module_name):
                print(f"[PROACTIVE]: {class_name} disabled by config.")
                continue
            try:
                module = __import__(
                    f"core.monitors.{module_name}", fromlist=[class_name]
                )
                monitor_class = getattr(module, class_name)
                monitor = monitor_class(event_queue=self.event_queue, config=cfg)
                self.monitors.append(monitor)
                print(f"[PROACTIVE]: {class_name} loaded.")
            except ImportError as exc:
                print(f"[PROACTIVE]: Module not found for {class_name}: {exc}")
            except AttributeError as exc:
                print(f"[PROACTIVE]: Class {class_name} missing in module: {exc}")
            except Exception as exc:
                print(f"[PROACTIVE]: Failed to load {class_name}: {exc}")

        # Load AGI Extension monitors from core.* (not core.monitors.*)
        try:
            from core.feature_flags import is_enabled
        except ImportError:
            is_enabled = lambda name, default=True: True

        for module_name, class_name in agi_monitors:
            cfg = monitor_configs.get(module_name, {"enabled": True})
            if not cfg.get("enabled", True) or not is_enabled(module_name):
                print(f"[PROACTIVE]: {class_name} (AGI) disabled by config.")
                continue
            try:
                module = __import__(f"core.{module_name}", fromlist=[class_name])
                monitor_class = getattr(module, class_name)
                monitor = monitor_class(event_queue=self.event_queue, config=cfg)
                self.monitors.append(monitor)
                print(f"[PROACTIVE]: {class_name} (AGI) loaded.")
            except ImportError as exc:
                print(f"[PROACTIVE]: AGI module not found for {class_name}: {exc}")
            except AttributeError as exc:
                print(f"[PROACTIVE]: AGI class {class_name} missing: {exc}")
            except Exception as exc:
                print(f"[PROACTIVE]: Failed to load AGI {class_name}: {exc}")


    # ── Quiet-hour & cooldown logic ───────────

    def _is_quiet_hours(self) -> bool:
        """Return ``True`` if the current local time falls within quiet hours."""
        qh = self.config.get("quiet_hours", {})
        if not qh.get("enabled", False):
            return False
        try:
            now = datetime.now()
            start_h, start_m = map(int, qh.get("start", "23:00").split(":"))
            end_h, end_m = map(int, qh.get("end", "07:00").split(":"))
            current_minutes = now.hour * 60 + now.minute
            start_minutes = start_h * 60 + start_m
            end_minutes = end_h * 60 + end_m
            if start_minutes > end_minutes:  # Overnight span
                return current_minutes >= start_minutes or current_minutes < end_minutes
            return start_minutes <= current_minutes < end_minutes
        except Exception as e:
            log_warn("proactive_orchestrator", f"Quiet hours time parse failed: {e}")
            return False

    def _check_cooldown(self, event: ProactiveEvent) -> bool:
        """Return ``True`` if the event's category is still on cooldown."""
        cooldown_seconds = self.COOLDOWN_MAP.get(event.priority, 300)
        last_time = self.cooldowns.get(event.category, 0)
        return (time.time() - last_time) < cooldown_seconds

    # ── Event processing ──────────────────────

    def _process_event(self, event: ProactiveEvent) -> None:
        """Decide whether to announce a single proactive event."""

        # 1. Quiet hours: suppress everything except CRITICAL
        if self._is_quiet_hours() and event.priority > 1:
            return

        # 2. Cooldown check
        if self._check_cooldown(event):
            return

        # 3. Record cooldown timestamp
        self.cooldowns[event.category] = time.time()

        # 4. Append to in-memory history (capped at 50)
        self.event_history.append({
            "timestamp": event.timestamp,
            "category": event.category,
            "priority": event.priority,
            "title":    event.title,
            "message":  event.message,
        })
        if len(self.event_history) > 50:
            self.event_history = self.event_history[-50:]

        # 5. Persist to SQLite
        try:
            from core.database import log_proactive_event
            log_proactive_event(
                event.category, event.priority,
                event.title, event.message,
                json.dumps(event.data),
            )
        except Exception as e:
            from core.jarvis_logger import log_error
            log_error("proactive", "persist_event", e)

        # 6. Console log
        icon = self.PRIORITY_ICONS.get(event.priority, "⚪")
        print(f"\n[{icon} PROACTIVE | {event.category.upper()}]: {event.title}")
        print(f"   → {event.message}")

        # 7. Emit to Qt UI (toast notification)
        if self.ui_signal:
            try:
                self.ui_signal.emit(
                    "proactive",
                    f"PROACTIVE_TOAST:{icon} {event.title}|{event.message}",
                )
            except Exception as e:
                from core.jarvis_logger import log_error
                log_error("proactive", "ui_signal_emit", e)

        # 8. Broadcast to WebSocket clients
        try:
            from core.ws_server import manager as ws_manager
            ws_manager.broadcast({
                "type":      "proactive_event",
                "category":  event.category,
                "priority":  event.priority,
                "title":     event.title,
                "message":   event.message,
                "timestamp": event.timestamp,
            })
        except Exception as e:
            from core.jarvis_logger import log_error
            log_error("proactive", "ws_broadcast", e)

        # 9. Speak aloud for priority 1–3 (CRITICAL / HIGH / MEDIUM)
        if event.priority <= 3:
            # Check if live voice is active — suppress proactive voice interruptions
            try:
                from live_voice import get_active_live_voice
                _lv = get_active_live_voice()
                if _lv and (_lv.is_connected or getattr(_lv, "_is_recording", False)):
                    return
            except Exception:
                pass

            try:
                from core.voice import speak, is_speaking

                # Fix #11: Rate-limit spoken alerts
                now = time.time()
                # Drop alerts older than 1 hour from tracking list
                self._voice_alert_times = [t for t in self._voice_alert_times if now - t < 3600]

                _too_frequent = (
                    len(self._voice_alert_times) >= self._max_voice_per_hour
                    or (
                        self._voice_alert_times
                        and (now - self._voice_alert_times[-1]) < self._min_voice_gap_sec
                        and event.priority > 1   # CRITICAL always speaks immediately
                    )
                )

                # Check if voice is busy or talking
                busy = False
                try:
                    import core.voice as _v
                    busy = getattr(_v, "is_speaking", False)
                except Exception:
                    pass

                if _too_frequent and event.priority > 1:
                    print(f"[PROACTIVE RATE-LIMIT]: Voice suppressed for '{event.title}' (limit reached)")
                elif not busy:
                    self._voice_alert_times.append(now)
                    self._speak_executor.submit(speak, event.message)
            except Exception as e:
                from core.jarvis_logger import log_error
                log_error("proactive", "speak_alert", e)

    # ── Daily briefing ────────────────────────

    def _run_daily_briefing(self) -> None:
        """Generate and announce the daily briefing on first boot."""
        try:
            from core.monitors.daily_briefing import DailyBriefing

            briefing = DailyBriefing()
            monitors_data: dict = {}
            for mon in self.monitors:
                monitors_data[getattr(mon, "name", type(mon).__name__)] = getattr(
                    mon, "last_data", {}
                )
            text = briefing.generate_briefing(monitors_data)
            if text:
                event = ProactiveEvent(
                    priority=5,
                    category="briefing",
                    title="Daily Briefing",
                    message=text,
                    data={},
                    timestamp=time.time(),
                )
                self._process_event(event)
                self.daily_briefing_done = True
        except ImportError:
            print("[PROACTIVE]: Daily briefing module not found — skipping.")
        except Exception as exc:
            print(f"[PROACTIVE]: Daily briefing error: {exc}")

    # ── Public helpers ────────────────────────

    def enqueue_event(self, event: ProactiveEvent) -> None:
        """Thread-safe way for external code to push an event."""
        self._event_counter += 1
        self.event_queue.put((event.priority, self._event_counter, event))

    def get_event_history(self) -> list:
        """Return a copy of recent event history for the dashboard."""
        return list(self.event_history)

    # ── Main loop ─────────────────────────────

    def run(self) -> None:
        """Thread entry-point — runs until ``stop()`` is called."""
        print("\n[PROACTIVE AGENCY]: Initializing Proactive Orchestrator...")

        if not self.config.get("enabled", True):
            print("[PROACTIVE AGENCY]: Disabled by configuration. Exiting.")
            return

        self._init_monitors()

        # Start all monitors with a stagger to avoid resource contention
        for monitor in self.monitors:
            if self._stop_event.is_set():
                return
            try:
                monitor.start()
            except Exception as exc:
                print(f"[PROACTIVE]: Monitor start error: {exc}")
            if self._stop_event.wait(0.2):
                return

        print(
            f"[PROACTIVE AGENCY]: {len(self.monitors)} monitors active. "
            f"Intelligence Engine running."
        )

        # Give monitors time to gather initial data
        self._stop_event.wait(15)
        if self._stop_event.is_set():
            return

        # Daily briefing
        briefing_cfg = self.config.get("daily_briefing", {})
        if briefing_cfg.get("enabled", True) and not self.daily_briefing_done:
            self._run_daily_briefing()

        # ── Main intelligence loop ──
        while not self._stop_event.is_set():
            try:
                # Drain the event queue
                events_batch: list[ProactiveEvent] = []
                while not self.event_queue.empty():
                    try:
                        _priority, _counter, event = self.event_queue.get_nowait()
                        events_batch.append(event)
                    except queue.Empty:
                        break

                # Sort by priority (lower number = higher urgency)
                events_batch.sort(key=lambda e: e.priority)

                # Process every surviving event
                for event in events_batch:
                    self._process_event(event)

            except Exception as exc:
                log_warn("proactive_orchestrator", f"Orchestrator loop error: {exc}")

            # Sleep 5 s (interruptible by stop())
            self._stop_event.wait(5)

    def stop(self) -> None:
        """Gracefully shut down the orchestrator and all monitors."""
        print("[PROACTIVE AGENCY]: Shutting down…")
        self._stop_event.set()
        for monitor in self.monitors:
            try:
                monitor.stop()
            except Exception as e:
                log_warn("proactive_orchestrator", f"Monitor stop error: {e}")
        print("[PROACTIVE AGENCY]: All monitors stopped.")
